name: Other tests

on:
  workflow_call:
    inputs:
      test-name:
        required: true
        type: string
      os:
        required: true
        type: string
env:
  CLASSPATH: ":/usr/lib/opensourcecobol4j/libcobj.jar"

jobs:
  test-other:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.os }}
    steps:
      - name: Get the artifact name
        run: echo ARTIFACT_NAME=${{ inputs.os }} | sed 's/:/-/g' >> $GITHUB_ENV

      - uses: actions/download-artifact@v3
        with:
          name: opensourcecobol4j-${{ env.ARTIFACT_NAME }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install dependencies on Ubuntu 22.04
        if: inputs.os == 'ubuntu:22.04'
        run: |
          apt update -y
          apt install -y build-essential

      - name: Install dependencies on AlmaLinux 9
        if: inputs.os == 'almalinux:9'
        run: |
          dnf -y update
          dnf install -y gcc make diffutils

      - name: Install opensource COBOL 4J
        run: |
          tar zxf opensourcecobol4j.tar.gz
          mv opensourcecobol4j/* .
          make install
      
      - name: Run tests ${{ inputs.test-name }}
        run: |
          cd tests/
          ./${{ inputs.test-name }}