name: NIST tests

on:
  workflow_call:
    inputs:
      test-name:
        required: true
        type: string
      check-result:
        required: false
        default: true
        type: boolean

env:
  CLASSPATH: ":/usr/lib/opensourcecobol4j/libcobj.jar"

jobs:
  test-other:
    strategy:
      matrix:
        os: ["ubuntu:22.04", "almalinux:9"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
    steps:
      - name: Get the artifact name
        run: echo ARTIFACT_NAME=${{ matrix.os }} | sed 's/:/-/g' >> $GITHUB_ENV

      - uses: actions/download-artifact@v3
        with:
          name: opensourcecobol4j-${{ env.ARTIFACT_NAME }}

      - name: Install dependencies on Ubuntu 22.04
        if: matrix.os == 'ubuntu:22.04'
        run: |
          apt update -y
          apt install -y default-jdk build-essential

      - name: Install dependencies on AlmaLinux 9
        if: matrix.os == 'almalinux:9'
        run: |
          dnf -y update
          dnf install -y java-17-openjdk-devel gcc make perl

      - name: Install opensource COBOL 4J
        run: |
          tar zxf opensourcecobol4j.tar.gz
          mv opensourcecobol4j/* .
          make install
      
      - name: Run tests ${{ inputs.test-name }}
        if: ${{ inputs.check-result }}
        run: |
          cd tests/cobol85/${{ inputs.test-name }}
          make test
          test "$(cat report.txt | tail -n 3 | head -n 1 | awk '{print $4}')" = '(100.00%)'

      - name: Run tests ${{ inputs.test-name }}
        if: not ${{ inputs.check-result  != 'true' }}
        run: |
          cd tests/cobol85/${{ inputs.test-name }}
          make test